name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs:
  Build and Deploy: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest
    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v2.3.1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

      - name: Install and Build # 步骤2
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
