name: build-and-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@master
      - name: 设置 node
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: 安装与构建
        run: npm install && npm run build
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          rm: 1
          source: 'dist'
          target: 'nginx/html/blog'
          strip_components: 1
